SistemaGestion/Models/ViewModels/DiferenciaView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaGestion.Models.ViewModels
{
    public class DiferenciaView
    {
        public DateTime Fecha { get; set; }

        public int Centro { get; set; }

        public string Autorizador { get; set; }

        public string Tarjeta { get; set; }

        public int Local { get; set; }

        public int TipoAsiento { get; set; }

        public int TipoAsiento2 { get; set; }

        public int CuentaContable { get; set; }
        
        public int CuentaContable2 { get; set; }

        public List<CuentaContables> ListaCuentas1 {get;set;}

        public List<CuentaContables> ListaCuentas2 { get; set; }
        public decimal Monto { get; set; }

       


        public class CuentaContables
        {
            public int Codigo { get; set; }

            public string NumeroCuenta { get; set; }

            public string Descripcion { get; set; }
            public string Nombre { get; set; }
        }

        public static IEnumerable<SelectListItem> Asiento()
        {
            IList<SelectListItem> lista = new List<SelectListItem>();
            lista.Add(new SelectListItem() { Text = "40", Value = "40" });
            lista.Add(new SelectListItem() { Text = "50", Value = "50" });
            return lista;
        }

        

    }

}

SistemaGestion/Controllers/ConciliacionPagosController.cs
using OfficeOpenXml;
using SistemaGestion.Models;
using SistemaGestion.Models.DAO;
using SistemaGestion.Models.ViewModels;
using SistemaGestion.Models.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;
using Newtonsoft.Json;

namespace SistemaGestion.Controllers
{
    [Authorize]
    public class ConciliacionPagosController : Controller
    {
        // GET: ConciliacionPagos
        #region Objetos
        private ConciliacionPagos carga = new ConciliacionPagos();
        private Negocio Ng = new Negocio();
        private CuentaContables Cuenta = new CuentaContables();
        private string Login = Thread.CurrentPrincipal.Identity.Name;
        private UserLoginView user = new UserLoginView();

        public ConciliacionPagosController()
        {
            user = JsonConvert.DeserializeObject<UserLoginView>(Login);
        }
        #endregion
        public ActionResult Index()
        {
            return View();
        }

        [AuthorizeRoles("Administrador", "Cuadratura")]
        #region ConciliacionAutomatica
        public ActionResult ConciliacionAuto()
        {
            List<ConciliacionAutoPagos> lst = new List<ConciliacionAutoPagos>();
            return View(lst);
        }

        [HttpPost]
        public ActionResult ObtenerConciliacionAuto(DateTime Fecha, int local)
        {
            var ConciliadasAuto = carga.Conciliacion(Fecha);
            ConciliadasAuto.DetalleConciliacionPagos.Where(x => x.IdTienda == local).ToList();
            return PartialView("_Auto", ConciliadasAuto);
        }

        //Verifica si la fecha ingresada existe o no
        [HttpPost]
        public JsonResult ValidadorConciliacionAuto(DateTime Fecha)
        {
            List<ConciliaciondePagos> lst = new List<ConciliaciondePagos>();
            lst = carga.GetConciliacion(Fecha);
            var resultado = new ResponseModel();
            if (lst.Any())
            {
                resultado.error = false;
                resultado.respuesta = "Esta Fecha ya fue conciliada.. Desea volver a Generar?";
                return Json(resultado);
            }
            else
            {
                resultado = carga.Conciliacion_Automatica(Fecha);
                if (!resultado.error)
                {
                    Auditoria auditoria = new Auditoria();
                    var UserJson = Thread.CurrentPrincipal.Identity.Name;
                    var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
                    auditoria.IdUsuario = Deserialize.idUsuario;
                    auditoria.Descripcion = "Se Genero Reproceso de la Conciliacion Automatica Pagos por el usurio :" + Deserialize.LoginName;
                    auditoria.Fecha = DateTime.Now;
                    Ng.Auditoria(auditoria);
                }
                return Json(resultado);
            }

        }

        [HttpPost]
        public JsonResult ConciliacionAuto(DateTime Fecha)
        {
           
            var resultado = new ResponseModel();
            resultado = carga.Conciliacion_Automatica(Fecha);
            if (!resultado.error)
            {
                Auditoria auditoria = new Auditoria();
                var UserJson = Thread.CurrentPrincipal.Identity.Name;
                var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
                auditoria.IdUsuario = Deserialize.idUsuario;
                auditoria.Descripcion = "Se Genero Conciliacion Automatica por el usurio :" + Deserialize.LoginName;
                auditoria.Fecha = DateTime.Now;
                Ng.Auditoria(auditoria);
            }
            return Json(resultado);

        }

        [HttpPost]
        public ActionResult ExcelConciliadasA(DateTime Fecha)
        {
            using (ExcelPackage excelPackage = new LibrosExcel().ReportConciliadasAPagos(carga.Conciliacion(Fecha)))
            {
                MemoryStream memoryStream = new MemoryStream();
                excelPackage.SaveAs((Stream)memoryStream);
                string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                DateTime dateTime = DateTime.Now;
                dateTime = dateTime.Date;
                string fileDownloadName = "ConciliadasAutomaticaPagos_" + dateTime.ToString("dd/MM/yyyy") + ".xlsx";
                memoryStream.Position = 0L;
                return File((Stream)memoryStream, contentType, fileDownloadName);
            }
        }

        #endregion

        #region Conciliadas Manual

        public ActionResult ConciliacionManual()
        {
            List<fn_ConciliacionPagos_Manual_aPI_Result> lst = new List<fn_ConciliacionPagos_Manual_aPI_Result>();
            return View(lst);
        }
        [HttpPost]
        public ActionResult ConciliacionManual(DateTime Fecha, int local)
        {
            List<fn_ConciliacionPagos_Manual_aPI_Result> lst = new List<fn_ConciliacionPagos_Manual_aPI_Result>();
            lst = carga.ConciliacionManaul(Fecha, local);
            return PartialView("_NoConciliacion", lst);
        }

        [HttpPost]
        public ActionResult AutotbkMontotbk(string Autorizador, decimal Monto, DateTime Fecha, int Tienda)
        {
            ManualView Manual = new ManualView();
            List<fn_ConciliacionPagos_Manual_aPI_Result> lst = new List<fn_ConciliacionPagos_Manual_aPI_Result>();
            var local = Ng.getTienda(Tienda);
            Manual.AutorizadorTbk = Autorizador;
            Manual.MontoTbk = Monto;
            Manual.Fecha = Fecha;
            Manual.Centro = Tienda;
            Manual.LstMp = new List<ManualView.Mp>();
            Manual.Local = local.Local;
            lst = carga.GetConciliacionManualMP(Fecha, local.Local, Monto);
            foreach (var item in lst)
            {
                ManualView.Mp mp = new ManualView.Mp();
                mp.AutorizadorMP = item.CodAutorizador;
                mp.Monto = item.MontoAfecto.Value;
                mp.Trx = item.Trx.Value;
                mp.Nombre = ("Autorizador: " + item.CodAutorizador + " Monto: " + item.MontoAfecto);

                Manual.LstMp.Add(mp);
            }

            return PartialView("_ConciliarXMontoMP", Manual);

        }

        public JsonResult AgregarConciliacionManual(ManualView manual)
        {
            ResponseModel response = new ResponseModel();
            ManualView Manual = new ManualView();
            response = carga.InserConciliacionManual(manual);
            if (!response.error)
            {
                Auditoria auditoria = new Auditoria();
                var UserJson = Thread.CurrentPrincipal.Identity.Name;
                var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
                auditoria.IdUsuario = Deserialize.idUsuario;
                auditoria.Descripcion = " Se inserto la conciliacion Manual por el usuario :" + Deserialize.LoginName;
                auditoria.Fecha = DateTime.Now;
                Ng.Auditoria(auditoria);
            }
            return Json(response);
        }
        
        public ActionResult ConciliadasManual(DateTime Fecha, int local)
        {
          
           var lst = carga.Conciliacion(Fecha);
            lst.DetalleConciliacionPagos.Where(x => x.IdTienda == local).ToList();
            return PartialView("_ConciliadasManual", lst);
        }

        [HttpPost]
        public ActionResult ExcelConciliadasM(DateTime Fecha)
        {
            using (ExcelPackage excelPackage = new LibrosExcel().ReportConciliadasMPagos(carga.Conciliacion(Fecha)))
            {
                MemoryStream memoryStream = new MemoryStream();
                excelPackage.SaveAs((Stream)memoryStream);
                string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                DateTime dateTime = DateTime.Now;
                dateTime = dateTime.Date;
                string fileDownloadName = "ConciliadasAutomaticaPagos" + Fecha.ToString("dd/MM/yyyy") + ".xlsx";
                memoryStream.Position = 0L;
                return File((Stream)memoryStream, contentType, fileDownloadName);
            }
        }

        #endregion

        #region ConciliacionDiferencias
        public ActionResult DifConciliacion()
        {
            List<fn_ConciliacionPagos_Manual_aPI_Result> lst = new List<fn_ConciliacionPagos_Manual_aPI_Result>();
            return View(lst);
        }
        [HttpPost]
        public ActionResult DifConciliacion(DateTime Fecha, int local)
        {
            List<fn_ConciliacionPagos_Manual_aPI_Result> lst = new List<fn_ConciliacionPagos_Manual_aPI_Result>();
            lst = carga.ListaDiferencias(Fecha, local);
            return PartialView("_Reversas", lst);
        }

        public ActionResult Diferencias(string Autorizador, decimal Monto, DateTime Fecha, int Tienda)
        {
            DiferenciaView Dif = new DiferenciaView();
            List<fn_ConciliacionPagos_Manual_aPI_Result> lst = new List<fn_ConciliacionPagos_Manual_aPI_Result>();
            List<Cuenta> lstCuenta = new List<Cuenta>();
            var local = Ng.getTienda(Tienda);
            Dif.Autorizador = Autorizador;
            Dif.Monto = Monto;
            Dif.Fecha = Fecha;
            Dif.Centro = local.Local;
            Dif.Local = Tienda;
            Dif.ListaCuentas1 = new List<DiferenciaView.CuentaContables>();
            Dif.ListaCuentas2 = new List<DiferenciaView.CuentaContables>();
            lstCuenta = Cuenta.ObtenerCuentasContables();
            foreach (var item in lstCuenta)
            {
                DiferenciaView.CuentaContables CC = new DiferenciaView.CuentaContables();
                CC.Codigo = item.Codigo;
                CC.NumeroCuenta = item.NumeroCuenta;
                CC.Descripcion = item.Descripcion;

SistemaGestion/Views/ConciliacionPagos/ConciliacionAuto.cshtml
@model List<SistemaGestion.Models.ConciliacionAutoPagos>
@{
    ViewBag.Title = "ConciliacionAuto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <br />
                    @*<nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active" aria-current="page">Transacciones</li>
                                <li class="breadcrumb-item"><a href="@Url.Action("TransaccionesTotales", "ApiTransbank")">Totales</a></li>

                            </ol>
                        </nav>*@

                    <div class="row">

                        <div class="col-sm-12">
                            <div class="card border-secondary">
                                <div class="card-header bg-secondary text-white">
                                    Conciliacion Automatica
                                </div>
                                @using (Html.BeginForm("ExcelPagos", "ConciliacionPagos", FormMethod.Post, new { id = "fromConciliacionAutomatico", role = "form" }))
                                {
                                    <div class="card-body">
                                        <div class="row align-items-end">
                                            <div class="col-sm-2">
                                                <div class="form-group mb-0">
                                                    <label for="txtRucProveedor" class="col-form-label col-form-label-sm">Fecha Inicio:</label>
                                                    <input type="date" class="form-control form-control-sm model" id="Fecha" name="Fecha" autocomplete="off" value="@DateTime.Today.ToString("yyyy-MM-dd")">

                                                </div>
                                            </div>
                                            <div class="col-sm-3">
                                                <div class="form-group mb-0">
                                                    <label for="txtRucProveedor" class="col-form-label col-form-label-sm">Tienda:</label>
                                                    <select class="form-control form-control-sm model" id="cboTienda" name="cboTienda"></select>
                                                </div>
                                            </div>
                                            <div class="col-sm-2">
                                                <div class="form-group mb-0">
                                                    <button type="button" class="btn btn-sm btn-primary btn-block" id="btnConciliar"><i class="fas fa-search"></i> N 1° Conciliar Por Fecha</button>
                                                </div>
                                            </div>
                                          <div class="col-sm-2">
                                                <div class="form-group mb-0">
                                                    <button type="button" class="btn btn-sm btn-danger btn-block" id="btnBuscar"><i class="fas fa-search"></i> N° 2 Conciliadas</button>
                                                </div>
                                            </div>
                                        <div class="col-sm-2">
                                                <div class="form-group mb-0">
                                                    <label for="btnBuscar" class="col-form-label col-form-label-sm invisible">Direccion:</label>
                                                    <button class="btn btn-sm btn-success btn-block" id="DescargarConManual" type="submit" role="button"><i class="fa fa-file-excel"> </i> Descargar</button>
                                                </div>
                                            </div>
                                        </div>





                                    </div>
                                }
                            </div>
                            <div id="totales">

                            </div>
                        </div>
                    </div>


                </div>
            </main>
        </div>
    </div>
</body>
@section scripts{
    <script>
        $(document).ready(function () {
            $('#tablaVacia').DataTable(
                {
                    responsive: true,
                     "language": {
                   url: "@Url.Content("~/Content/datatable/js/datatable_spanish.json")"
               }
                });
         $('#DescargarConManual').click(function (event) {
            event.preventDefault();
            var url = '@Url.Action("ExcelConciliadasA", "ConciliacionPagos")';
            var Fecha = $("#Fecha").val();
            var Tienda = $("#cboTienda").val();
            console.log(Fecha);
            console.log(Tienda);
            //var tipo = $("#TypeReporte").val();
            DownloadFileFechasEntre(Fecha, Tienda, url);
        });
             $(function (){
                 $("#btnBuscar").click(function () {
                event.preventDefault();
                var result = confirm("Desea Cargar Las Conciliadas Automaticamente?");
                 if (result){
                    $('#cargal').modal('show');
                    var url = "@Url.Action("ObtenerConciliacionAuto", "ConciliacionPagos")";
                    var manejarErrorAjax = "Eror";
                    var Fecha = $("#Fecha").val();
                    var local = $("#cboTienda").val();
                    var data = { Fecha: Fecha, local:local };
                    $.post(url, data).done(function (data) {
                        setTimeout(bajar, 1000);
                        setTimeout(Subir, 2000);

                        function bajar() {
                            $('#cargal').modal('hide');

                        }
                        function Subir() {
                            $('#totales').html(data);
                            $('#totales').show();
                        }

                    }).fail(manejarErrorAjax);

                     }
                });

             })

              $(function (){
                  $("#btnConciliar").click(function () {
                event.preventDefault();
                var result = confirm("Desea Generar Conciliacion Automatica?");
                if (result){
                    $('#cargal').modal('show');
                    var url = "@Url.Action("ValidadorConciliacionAuto", "ConciliacionPagos")";
                    var manejarErrorAjax = "Eror";
                    var Fecha = $("#Fecha").val();
                    var data = { Fecha: Fecha};
                    $.post(url, data).done(function (res) {
                        if (res.error == false) {
                            var Confirmacion = confirm(res.respuesta);
                            if (Confirmacion) {
                                var url2 = "@Url.Action("ConciliacionAuto", "ConciliacionPagos")";
                                $.post(url2, data).done(function (res2) {
                                    setTimeout(carga, 3000);
                                    /* setTimeout(CerrarVistaP, 10000);*/
                                    setTimeout(mostrarMensaje, 4000);
                                    setTimeout(bajaModal, 6000);
                                    function carga() {

                                        $("#cargal").modal('hide');

                                    };
                                    //function CerrarVistaP() {
                                    //    $('#modal').modal('hide');
                                    //};
                                    function bajaModal() {
                                        $('#cargarMensajes').modal('hide');
                                        $('#modal').modal('hide');


                                    };

                                    function mostrarMensaje() {
                                        $("#cargarMensajes").modal('show');
                                        $('#mensajeLoad').html(res2.respuesta);

                                    };

                                });
                            }
                            
                        }
                        else {
                            setTimeout(carga, 3000);
                            setTimeout(mostrarMensaje, 4000);
                            setTimeout(bajaModal, 6000);
                            function carga() {
                                $("#cargal").modal('hide');
                                //$("#cargarMensajes").modal('show');
                                //$('#mensajeLoad').html(r.respuesta);
                            };
                            function bajaModal() {

                                $("#cargarMensajes").modal('hide');

                            };

                            function mostrarMensaje() {
                                $("#cargarMensajes").modal('show');
                                $('#mensajeLoad').html(res.respuesta);

                            };
                        }


                    }).fail(manejarErrorAjax);

                }
            });

        })

        });

        jQuery.ajax({
            url: $.MisUrls.url._TiendaPorNombre,
            type: "GET",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                $("<option>").attr({ "value": 0 }).text("-- Seleccionar todas--").appendTo("#cboTienda");
                $.each(data.data, function (i, item) {
                    $("<option>").attr({ "value": item.Codigo }).text(item.Nombre_Centro).appendTo("#cboTienda");

                })
            },
            error: function (error) {
                console.log(error)
            },

        });

        function DownloadFileFechasEntre(Fecha, Tienda, urlAc) {


            var url = urlAc;
            //var Fecha = F;
            //var fechaFin = fechaT;
            //var tipoR = tipo;

            var list = [];
            var fileName = '';
            list.push({ fileName: fileName });

            $('#cargal').modal('show');
            $.ajax({
                url: url,
                type: "post",
                data: { Fecha: Fecha, Tienda: Tienda },
                xhrFields: {
                    responseType: 'blob'
                },
                success: function (data, textStatus, xhr) {
                    var filename = list[0].filename;
                    var disposition = xhr.getResponseHeader('Content-Disposition');
                    if (disposition && disposition.indexOf('attachment') !== -1) {
                        var filenameRegex = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/;
                        var matches = filenameRegex.exec(disposition);
                        if (matches != null && matches[1]) filename = matches[1].replace(/['"]/g, '');
                        var a = document.createElement('a');
                        var url = window.URL.createObjectURL(data);
                        a.href = url;
                        a.download = filename;
                        document.body.append(a);
                        a.click();
                        a.remove();
                        window.URL.revokeObjectURL(url);
                    }
                    else {
                        getErrorToastMessage("ERROR AL DESCARGAR ARCHIVO");
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {

                },
                complete: function () {
                    //var interfaz = list[0];
                    //deleteArchivo(list);
                    setTimeout(function () {
                        $("#cargal").modal('hide');
                    }, 1500);

                }
            });
        }

    </script>
}

SistemaGestion/Views/ConciliacionPagos/_ConciliarXMontoMP.cshtml
@model SistemaGestion.Models.ViewModels.ManualView

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Obtener No Conciliadas de Tbk Con Mp</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                @using (Html.BeginForm("AgregarConciliacionManual", "ConciliacionPagos", FormMethod.Post, new { id = "AgregarConciliacionManual", role = "form", enctype = "multipart/form-data" }))
                {
                    <div class="col-sm-12">

                        @Html.HiddenFor(x => x.Centro)
                        @Html.HiddenFor(x => x.Fecha)
                        @Html.HiddenFor(x => x.Local)

                        <input type="hidden" id="txtIdPersona" />
                        <div class="form-group">
                            <label for="txtNombre">Autorizador:</label>
                            @Html.TextBoxFor(x => x.AutorizadorTbk, new { @class = "form-control form-control-sm model", @readonly = "readonly" })
                            @*<input type="text" class="form-control form-control-sm model" id="Autorizador" name="Fecha" autocomplete="off" value="@Model.AutorizadorTbk">*@
                        </div>
                        <div class="form-group">
                            <label for="txtApellidos">Monto:</label>
                            @Html.TextBoxFor(x => x.MontoTbk, new { @class = "form-control form-control-sm model", @readonly = "readonly" })
                            @*<input type="text" class="form-control form-control-sm model" id="Monto" name="Fecha" autocomplete="off" value="@Model.MontoTbk">*@
                        </div>

                    </div>
                    <label for="txtNombre">Codigo de Autorizadores MP</label>
                    @Html.DropDownListFor(x => x.TrxMP, new SelectList(Model.LstMp.OrderBy(z => z.AutorizadorMP), "Trx", "Nombre"), "Seleccione MP...", new { @class = "form-control", name = "TrxMP" })
                }
            </div>



        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            <button type="submit" class="btn btn-primary" id="btcarga">Conciliar</button>
        </div>
    </div>
</div>

<script>
     $(function () {
         $("#btcarga").click(function () {
                event.preventDefault();
                var result = confirm("Desea Conciliar?");
                if (result) {
                    $('#cargal').modal('show');
                    var url = "@Url.Action("AgregarConciliacionManual", "ConciliacionPagos")";
                    var manejarErrorAjax = "Eror";
                    var parametros = $("#AgregarConciliacionManual").serialize();
                    var Fecha = $("#TrxMP").val();
                    console.log(Fecha);
                    $.post(url, parametros).done(function (res) {
                        if (res.error == false) {

                            setTimeout(carga, 3000);
                            setTimeout(mostrarMensaje, 4000);
                            setTimeout(bajaModal, 6000);
                            bajarModalConciliacion();
                            MostrarLista();

                            //setTimeout(bajarModalConciliacion, 8000);
                            function carga() {
                                $("#cargal").modal('hide');
                                //$("#cargarMensajes").modal('show');
                                //$('#mensajeLoad').html(r.respuesta);
                            };
                            function bajaModal() {

                                $("#cargarMensajes").modal('hide');
                                $("#totales").modal('hide');

                            };

                            function mostrarMensaje() {
                                $("#cargarMensajes").modal('show');
                                $('#mensajeLoad').html(res.respuesta);

                            };

                        /*    function Cargar*/


                        } else {

                            setTimeout(carga, 3000);
                            setTimeout(mostrarMensaje, 4000);
                            setTimeout(bajaModal, 6000);


                            function carga() {
                                $("#cargal").modal('hide');
                                //$("#cargarMensajes").modal('show');
                                //$('#mensajeLoad').html(r.respuesta);
                            };
                            function bajaModal() {

                                $("#cargarMensajes").modal('hide');

                            };

                            function mostrarMensaje() {
                                $("#cargarMensajes").modal('show');
                                $('#mensajeLoad').html(res.respuesta);

                            };

                        }
                        //$('.modal-backdrop').remove();

                    }).fail(manejarErrorAjax);

                }
            });

     })

    function MostrarLista() {
        $('#cargal').modal('show');
        var url = "@Url.Action("ConciliacionManual", "ConciliacionPagos")";
        var manejarErrorAjax = "Eror";
        var parametros = $("#AgregarConciliacionManual").serialize();
        var tienda = $("#Local").val();
        var Fecha = $("#Fecha").val();
        console.log('Entro en la vista de listas')
        console.log(tienda);
        var data = { Fecha: Fecha, local: tienda };
        $.post(url, data).done(function (data) {
            setTimeout(bajar, 1000);
            setTimeout(Subir, 2000);

            function bajar() {
                $('#cargal').modal('hide');

            }
            function Subir() {
                $('#totales').html(data);
                $('#totales').show();
            }

        }).fail(manejarErrorAjax);

    }
</script>