SistemaGestion/Controllers/AdministracionController.cs
using Newtonsoft.Json;
using SistemaGestion.Models;
using SistemaGestion.Models.DAO;
using SistemaGestion.Models.Repositorios;
using SistemaGestion.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SistemaGestion.Controllers
{
    [Authorize]
    public class AdministracionController : Controller
    {
        // GET: Administracion
        private AdministracionGS administracionGS = new AdministracionGS();
        private Negocio ng = new Negocio();
        private SisGesEntities3 db = new SisGesEntities3();


        public ActionResult ReprocesoTbk ()
        {
            return View();
        }

        public async Task<ActionResult> GetReprocesoTbk(DateTime Fecha)
        {
            ResponseModel response = new ResponseModel();
            response = await ng.ReprocesoTbk(Fecha);
            return Json(response);
        }

        public ActionResult ReprocesoInterfaces()
        {
            return View();
        }

        public async Task<ActionResult> GetReprocesoInterfaces(DateTime Fecha)
        {
            AdminUsuarios ADU = new AdminUsuarios();
            var UserJson = Thread.CurrentPrincipal.Identity.Name;
            var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
           
           

            ResponseModel response = new ResponseModel();
            
            response = await ng.GetToken(Deserialize);
            if (!response.error)
            {
                response = await ng.ReprocesoInterfaces(Fecha,response.token);
            }
          
            return Json(response);
        }


        public ActionResult Index()
        {

            return View();
        }

        public ActionResult BarridoGS()
        {

            return View();
        }
        [HttpPost]
        public ActionResult BarridoGS(DateTime Inicio, DateTime Fin)
        {
            ResponseModel response = new ResponseModel();
            if (!db.Periodo.Where(x => x.Cerrado == false && x.AnoNumero == Inicio.Year && x.MesNumero == Inicio.Month).Any())
            {
                response.error = true;
                response.respuesta = "El periodo que intenta reprocesar se encuentra cerrado";
                return Json(response);
            }
            var res = administracionGS.BarridoGS(Inicio, Fin);
            return Json(res);
        }

        public ActionResult ReprocesoMediosPagos()
        {

            return View();
        }
        [HttpPost]
        public ActionResult ReprocesoMediosPagos(DateTime Fecha)
        {
            ResponseModel response = new ResponseModel();

            if (!db.Periodo.Where(x => x.Cerrado == false && x.AnoNumero == Fecha.Year && x.MesNumero == Fecha.Month).Any())
            {
                response.error = true;
                response.respuesta = "El periodo que intenta reprocesar se encuentra cerrado";
                return Json(response);
            }

            response = administracionGS.GenerarMediosPagosPorFecha(Fecha);

            Auditoria auditoria = new Auditoria();

            var UserJson = Thread.CurrentPrincipal.Identity.Name;
            var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);

            auditoria.Descripcion = $"Se realiza reproceso de Medios de pago por el Usuario {Deserialize.LoginName}";
            auditoria.IdUsuario = Deserialize.idUsuario;
            auditoria.Fecha = DateTime.Now;

            ng.Auditoria(auditoria);

            return Json(response);
        }

        [HttpGet]
        public ActionResult CerrarPeriodo()
        {
            return View();
        }


   
        [HttpPost]
        public async Task<ActionResult> ENDPeriodo()
        {
            ResponseModel response = new ResponseModel();

            response = ng.CierrePeriodo();
            if (!response.error)
            {
                Auditoria auditoria = new Auditoria();

                var UserJson = Thread.CurrentPrincipal.Identity.Name;
                var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
                auditoria.Descripcion = $"{response.respuesta} por el Usuario {Deserialize.LoginName}";
                auditoria.IdUsuario = Deserialize.idUsuario;
                auditoria.Fecha = DateTime.Now;

                 await ng.GetAlertaCierre(auditoria.Descripcion);
                ng.Auditoria(auditoria);
            }

           

            return Json(response);
        }

    }
}

SistemaGestion/Views/Administracion/BarridoGS.cshtml
@{
    ViewBag.Title = "BarridoGS";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">


                    <div class="row">

                        <div class="col-sm-12">
                            <div class="card border-secondary">
                                <div class="card-header bg-secondary text-white">
                                    Recarga de Ventas
                                </div>

                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="txtRucProveedor" class="col-form-label col-form-label-sm">Fecha Inicio:</label>
                                                <input type="date" class="form-control form-control-sm model" id="Inicio" name="Inicio" autocomplete="off" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                                            </div>
                                        </div>
                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="txtRucProveedor" class="col-form-label col-form-label-sm">Fecha Fin:</label>
                                                <input type="date" class="form-control form-control-sm model" id="Fin" name="Fin" autocomplete="off" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                                            </div>
                                        </div>



                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="btcarga" class="col-form-label col-form-label-sm invisible">Reproce:</label>
                                                <button id="btnBuscar" type="button" class="btn btn-sm btn-danger btn-block"><i class="fas fa-search"></i> Reprocesar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                    <br>

                </div>
            </main>
        </div>
    </div>
</body>
@section scripts{
    <script>
   

        $("#btnBuscar").click(function () {

              var result = confirm("Desea Recargar Ventas?");
            if (result) {
                $('#cargal').modal('show');
                 var url = "@Url.Action("BarridoGS", "Administracion")";
                var manejarErrorAjax = "Eror";
                var Inicio = $("#Inicio").val();
                var Fin = $("#Fin").val();
               
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: { Inicio: Inicio, Fin: Fin },
                    success: function (response) {
                        if (response.error == true) {
                        
                            setTimeout(MostrarMensaje, 3000);
                            setTimeout(bajar, 5000);
                     

                        }
                        else {
                            setTimeout(MostrarMensaje, 3000);
                            setTimeout(bajar, 5000);
                     
                        }
                        function MostrarMensaje() {
                            $('#cargal').modal('hide');
                            $('#cargarMensajes').modal('show');
                            $('#mensajeLoad').html(response.respuesta);
                        };


                        function bajar() {

                            $('#cargarMensajes').modal('hide');
                        };


                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError);
                    }
                });
            }




        });
    </script>
}

SistemaGestion/Views/Administracion/CerrarPeriodo.cshtml
@{
    ViewBag.Title = "CerrarPeriodo";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">


                    <div class="row">

                        <div class="col-sm-12">
                            <div class="card border-secondary">
                                <div class="card-header bg-secondary text-white">
                                 Cerrar Periodo 
                                </div>

                                <div class="card-body">
                                    <div class="row">
                                       

                                        <div class="col-sm-3">
                                            <div class="form-group mb-0">
                                                <label for="btcarga" class="col-form-label col-form-label-sm invisible">Reproce:</label>
                                                <button id="btnBuscar" type="button" class="btn btn-sm btn-danger btn-block"><i class="fas fa-search"></i> Cerrar Periodo</button>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                    <br>

                </div>
            </main>
        </div>
    </div>
</body>
@section scripts{
    <script>


        $("#btnBuscar").click(function () {

              var result = confirm("Desea Cerrar El Periodo?");
            if (result) {
                $('#cargal').modal('show');
                 var url = "@Url.Action("ENDPeriodo", "Administracion")";
                var manejarErrorAjax = "Eror";
                //var Inicio = $("#Inicio").val();
                //var Fin = $("#Fin").val();

                $.ajax({
                    type: 'POST',
                    url: url,
             /*       data: { Inicio: Inicio, Fin: Fin },*/
                    success: function (response) {
                        if (response.error == true) {

                            setTimeout(MostrarMensaje, 5000);
                            setTimeout(bajar, 7000);


                        }
                        else {
                            setTimeout(MostrarMensaje, 5000);
                            setTimeout(bajar, 7000);

                        }
                        function MostrarMensaje() {
                            $('#cargal').modal('hide');
                            $('#cargarMensajes').modal('show');
                            $('#mensajeLoad').html(response.respuesta);
                        };


                        function bajar() {

                            $('#cargarMensajes').modal('hide');
                        };


                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError);
                    }
                });
            }




        });
    </script>
}

SistemaGestion/Views/Administracion/ReprocesoInterfaces.cshtml
@{
    ViewBag.Title = "ReprocesoInterfaces";
}


<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">


                    <div class="row">

                        <div class="col-sm-12">
                            <div class="card border-secondary">
                                <div class="card-header bg-secondary text-white">
                                    Recarga de CAAU/CAPA
                                </div>

                                <div class="card-body">
                                    <div class="row">

                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="txtFecha" class="col-form-label col-form-label-sm">Ingresar Fecha:</label>
                                                <input type="date" class="form-control form-control-sm model" id="Fecha" name="Fecha" autocomplete="off" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                                            </div>
                                        </div>



                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="btcarga" class="col-form-label col-form-label-sm invisible">Reproce:</label>
                                                <button id="btnBuscar" type="button" class="btn btn-sm btn-danger btn-block"><i class="fas fa-search"></i> Reprocesar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                    <br>

                </div>
            </main>
        </div>
    </div>
</body>
@section scripts{
    <script>


        $("#btnBuscar").click(function () {

              var result = confirm("Desea Reprocesar CAAU/CAPA?");
            if (result) {
                $('#cargal').modal('show');
                 var url = "@Url.Action("GetReprocesoInterfaces", "Administracion")";
                var manejarErrorAjax = "Eror";
                var Fecha = $("#Fecha").val();


                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {Fecha: Fecha },
                    success: function (response) {
                        if (response.error == true) {

                            setTimeout(MostrarMensaje, 3000);
                            setTimeout(bajar, 5000);


                        }
                        else {
                            setTimeout(MostrarMensaje, 3000);
                            setTimeout(bajar, 5000);

                        }
                        function MostrarMensaje() {
                            $('#cargal').modal('hide');
                            $('#cargarMensajes').modal('show');
                            $('#mensajeLoad').html(response.respuesta);
                        };


                        function bajar() {

                            $('#cargarMensajes').modal('hide');
                        };


                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError);
                    }
                });
            }




        });
    </script>
}

SistemaGestion/Views/Administracion/ReprocesoMediosPagos.cshtml
@{
    ViewBag.Title = "Reproceso Medios de Pago";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">


                    <div class="row">

                        <div class="col-sm-12">
                            <div class="card border-secondary">
                                <div class="card-header bg-secondary text-white">
                                    Recarga de Medios de Pago
                                </div>

                                <div class="card-body">
                                    <div class="row">

                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="txtFecha" class="col-form-label col-form-label-sm">Ingresar Fecha:</label>
                                                <input type="date" class="form-control form-control-sm model" id="Fecha" name="Fecha" autocomplete="off" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                                            </div>
                                        </div>



                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="btcarga" class="col-form-label col-form-label-sm invisible">Reproce:</label>
                                                <button id="btnBuscar" type="button" class="btn btn-sm btn-danger btn-block"><i class="fas fa-search"></i> Reprocesar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                    <br>

                </div>
            </main>
        </div>
    </div>
</body>
@section scripts{
    <script>


        $("#btnBuscar").click(function () {

              var result = confirm("Desea Reprocesar Medios de Pago?");
            if (result) {
                $('#cargal').modal('show');
                 var url = "@Url.Action("ReprocesoMediosPagos", "Administracion")";
                var manejarErrorAjax = "Eror";
                var Fecha = $("#Fecha").val();


                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {Fecha: Fecha },
                    success: function (response) {
                        if (response.error == true) {

                            setTimeout(MostrarMensaje, 3000);
                            setTimeout(bajar, 5000);


                        }
                        else {
                            setTimeout(MostrarMensaje, 3000);
                            setTimeout(bajar, 5000);

                        }
                        function MostrarMensaje() {
                            $('#cargal').modal('hide');
                            $('#cargarMensajes').modal('show');
                            $('#mensajeLoad').html(response.respuesta);
                        };


                        function bajar() {

                            $('#cargarMensajes').modal('hide');
                        };


                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError);
                    }
                });
            }




        });
    </script>
}

SistemaGestion/Views/Administracion/ReprocesoTbk.cshtml
@{
    ViewBag.Title = "ReprocesoTbk";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">


                    <div class="row">

                        <div class="col-sm-12">
                            <div class="card border-secondary">
                                <div class="card-header bg-secondary text-white">
                                    Recarga de TBK
                                </div>

                                <div class="card-body">
                                    <div class="row">

                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="txtFecha" class="col-form-label col-form-label-sm">Ingresar Fecha:</label>
                                                <input type="date" class="form-control form-control-sm model" id="Fecha" name="Fecha" autocomplete="off" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                                            </div>
                                        </div>



                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="btcarga" class="col-form-label col-form-label-sm invisible">Reproce:</label>
                                                <button id="btnBuscar" type="button" class="btn btn-sm btn-danger btn-block"><i class="fas fa-search"></i> Reprocesar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                    <br>

                </div>
            </main>
        </div>
    </div>
</body>
@section scripts{
    <script>


        $("#btnBuscar").click(function () {

              var result = confirm("Desea Reprocesar TBK?");
            if (result) {
                $('#cargal').modal('show');
                 var url = "@Url.Action("GetReprocesoTbk", "Administracion")";
                var manejarErrorAjax = "Eror";
                var Fecha = $("#Fecha").val();


                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {Fecha: Fecha },
                    success: function (response) {
                        if (response.error == true) {

                            setTimeout(MostrarMensaje, 3000);
                            setTimeout(bajar, 5000);


                        }
                        else {
                            setTimeout(MostrarMensaje, 3000);
                            setTimeout(bajar, 5000);

                        }
                        function MostrarMensaje() {
                            $('#cargal').modal('hide');
                            $('#cargarMensajes').modal('show');
                            $('#mensajeLoad').html(response.respuesta);
                        };


                        function bajar() {

                            $('#cargarMensajes').modal('hide');
                        };


                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError);
                    }
                });
            }




        });
    </script>
}