SistemaGestion/Models/LIBRO_VENTA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO_VENTA
    {
        public string Sociedad { get; set; }
        public string Centro { get; set; }
        public string ClaseDocumental { get; set; }
        public string NumeroDocto { get; set; }
        public string FechaContabilizacion { get; set; }
        public string Referencia { get; set; }
        public string FechaDocumento { get; set; }
        public string IndicadorImpuesto { get; set; }
        public string NombreCliente { get; set; }
        public string NumeroIdentFiscal { get; set; }
        public Nullable<decimal> Exento { get; set; }
        public Nullable<decimal> Afecto { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public decimal BaseImponibleMP { get; set; }
    }
}

SistemaGestion/Models/VENTAS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public int TRX { get; set; }
        public Nullable<short> TRX_Impreso { get; set; }
        public Nullable<short> Tipo_Trx { get; set; }
        public int Local { get; set; }
        public string Cajero { get; set; }
        public int Caja { get; set; }
        public System.DateTime Fecha_Venta { get; set; }
        public Nullable<System.DateTime> Fecha_Vta_Sistema { get; set; }
        public Nullable<System.DateTime> Fecha_Venta_Linea { get; set; }
        public short Caja_Fuera_Linea { get; set; }
        public short Modo_Entrenamiento { get; set; }
        public short Codigo_Anula { get; set; }
        public string Cliente { get; set; }
        public string Vendedor { get; set; }
        public short Venta_Iniciada { get; set; }
        public Nullable<decimal> Total_Venta { get; set; }
        public string Caja2 { get; set; }
        public string Folio_Documento { get; set; }
        public string Tipo_Documento { get; set; }
        public Nullable<int> Tipo_Impto { get; set; }
        public Nullable<decimal> Impto { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public decimal Bruto { get; set; }
    }
}

SistemaGestion/Controllers/GestionController.cs
using Newtonsoft.Json;
using OfficeOpenXml;
using SistemaGestion.Models;
using SistemaGestion.Models.DAO;
using SistemaGestion.Models.Security;
using SistemaGestion.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SistemaGestion.Controllers
{
    [Authorize]
    public class GestionController : Controller
    {
        // GET: Gestion
        #region Objetos
        private SisGesEntities3 db = new SisGesEntities3();
        private LibroVentaRepository carga = new LibroVentaRepository();
        private Negocio ng = new Negocio();
        private string Login = Thread.CurrentPrincipal.Identity.Name;
        private UserLoginView user = new UserLoginView();



        public GestionController()
        {
            user = JsonConvert.DeserializeObject<UserLoginView>(Login);
        }

        #endregion

        #region DetalleVenta
        [AuthorizeRoles("Administrador", "Cuadratura")]
        public ActionResult DetalleVenta()
        {
            return View();
        }

        public JsonResult Listar(string local, string documento, string fechaCon)
        {
          

            if (local == "0")
            {
                return Json("Debe Seleccionar Al menos una tienda");

            }

            if (documento == "" && fechaCon == "")
            {
                return Json(new { data = 0 }, JsonRequestBehavior.AllowGet);
            }

            if (documento != "")
            {
                documento = documento.Replace("TODOS", "");
            }

            var ListaDetalle = (from p in db.Proc_ListaDetalleVenta(fechaCon, local, documento)
                                select p).ToList();
            return Json(new { data = ListaDetalle }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ExcelVentas(string local, string documento, DateTime Fecha)
        {
            using (ExcelPackage excelPackage = new LibrosExcel().ReporteVentas(carga.DetalleVenta(local, documento, Fecha)))
            {
                MemoryStream memoryStream = new MemoryStream();
                excelPackage.SaveAs((Stream)memoryStream);
                string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                DateTime dateTime = DateTime.Now;
                dateTime = dateTime.Date;
                string fileDownloadName = "DetalleVenta" + dateTime.ToString("dd/MM/yyyy") + ".xlsx";
                memoryStream.Position = 0L;
                return File((Stream)memoryStream, contentType, fileDownloadName);
            }
        }
        #endregion

        #region LibroVenta
        [HttpGet]
        [AuthorizeRoles("Administrador", "Cuadratura")]
        public ActionResult LibroVenta()
        {
            List<Proc_ListaLibroVenta_Result> lst = new List<Proc_ListaLibroVenta_Result>();
            return View(lst);
        }

        public ActionResult AdminLibro(string local, DateTime Fecha)
        {

            List<Proc_ListaLibroVenta_Result> lst = carga.LibroVentaSap(local, Fecha);
           
            return PartialView("_DetalleLibro", lst);
        }
        #endregion

        #region LocalesACtivos
        // LocalesActivosPor Envio T000
        public JsonResult Tienda()
        {
            List<Locales> lst = null;
            lst = (from d in db.Proc_LOCALES_ACTIVOS()
                   select new Locales
                   {
                       Centro = d.Centro,
                       Nombre_Centro = d.Nombre_Centro,
                       Codigo = d.Codigo,

                   }).ToList();
            return Json(new { data = lst }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region TipoDocumento

        public JsonResult ClaseDocumento()
        {
            List<Documento> lst = null;
            lst = (from d in db.Proc_CLASE_DOCUMENTO()
                   select new Documento
                   {
                       NombreCorto = d.NombreCorto,
                       Descripcion = d.Descripcion,

                   }).ToList();
            return Json(new { data = lst }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region IdocGeneradosPorlasVentas

        [HttpGet]
        [AuthorizeRoles("Administrador", "Cuadratura")]
        public ActionResult Ventas()
        {
            List<Proc_ListaIdocVenta_Result> lst = new List<Proc_ListaIdocVenta_Result>();
            return View(lst);
        }

        public ActionResult OVentas(DateTime Fecha, string local)
        {
            List<Proc_ListaIdocVenta_Result> lst = carga.IdocdeVentas(Fecha, local);
            return PartialView("_Ventas",lst);
        }
        #endregion

        #region CargaDeLibroVenta       

        [HttpPost]
        public JsonResult CargaLibro(string Archivo = "lv.csv")
        {
            var resultado = carga.LibroVenta(Archivo);
            return Json(resultado);
        }

        public ActionResult saveLV(HttpPostedFileBase oFile)
        {
            ResponseModel response = new ResponseModel();

            string ruta = Server.MapPath("~/File/");
            if (oFile == null)
            {
                response.error = true;
                response.respuesta = "Debe cargar un archivo";
                return Json(response);
            }
            string extension = Path.GetExtension(oFile.FileName);

            if (extension.Equals(".XML"))
            {
                response = carga.CargaLibroVenta(oFile, ruta);
            }
            else if(extension.Equals(".xlsx"))
            {
                response = carga.CargaLibroVentaXLS(oFile, ruta);
            }
            else
            {
                response.error = true;
                response.respuesta = "La extencion no es correcta";
            }
            if (!response.error)
            {
                Auditoria auditoria = new Auditoria();
                var UserJson = Thread.CurrentPrincipal.Identity.Name;
                var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
                auditoria.IdUsuario = Deserialize.idUsuario;
                auditoria.Descripcion = "Se cargar libro de Venta por el usurio :" + Deserialize.LoginName;
                auditoria.Fecha = DateTime.Now;
                ng.Auditoria(auditoria);
            }

            return Json(response);
        }

        #endregion

        #region GenerarIdocReversaXTienda

        public ActionResult GenerarIdoc()
        {
            return View();
        }

        public ActionResult Reproceso(string Fecha, string Local)
        {
            DetalleDahsboard detalleDahsboard = new DetalleDahsboard();
            detalleDahsboard.Fecha = Fecha;
            detalleDahsboard.Centro = Local;
            return PartialView("_Reproceso", detalleDahsboard);
        }

        [HttpPost]
        public ActionResult ReprocesoNCFC(DateTime Fecha, string Local, string Documento)
        {
            if (Local != "")
            {
                Local = Local.Replace("T0", "");
            }

            int numLocal = int.Parse(Local);

            

            List<VENTAS> ventas = new List<VENTAS>();
            List<IdocNCFCView> NCFC = new List<IdocNCFCView>();
            ventas = db.VENTAS.Where(x => x.Fecha_Venta.Year == Fecha.Year && x.Fecha_Venta.Month == Fecha.Month && x.Fecha_Venta.Day == Fecha.Day && x.Local == numLocal && x.Tipo_Documento == Documento).ToList();
            foreach (var item in ventas)
            {
                IdocNCFCView NcFC = new IdocNCFCView();
                NcFC.Centro = item.Local;
                NcFC.FechaVenta = item.Fecha_Venta;
                NcFC.Folio = item.Folio_Documento;
                NcFC.TipoDoc = item.Tipo_Documento;
                NcFC.Monto = item.Total_Venta.Value;
                NcFC.Rut = item.Cliente;
                NcFC.isCheck = false;

                NCFC.Add(NcFC);

            }
            return PartialView("_ReprocesoNCFC", NCFC);
        }

        public JsonResult FoliosNCFC(List<IdocNCFCView> ListNCFC) {
            var resultado = new ResponseModel();
            //DateTime fecha = 
            DateTime FechaDataTime = ListNCFC.GroupBy(x => x.FechaVenta).Select(x => x.Key).FirstOrDefault(); 

            if (!db.Periodo.Where(x => x.Cerrado == false && x.AnoNumero == FechaDataTime.Year && x.MesNumero == FechaDataTime.Month).Any())
            {
                resultado.error = true;
                resultado.respuesta = "El periodo que intenta reprocesar se encuentra cerrado";
                return Json(resultado);
            }

            resultado = carga.ListaFoliosNCFC(ListNCFC);
            var ls = ListNCFC.GroupBy(x =>  new { x.Centro, x.FechaVenta }).Select(x=> new IdocNCFCView() { Centro = x.Key.Centro, FechaVenta = x.Key.FechaVenta }).FirstOrDefault();
            if (resultado.error)
            {
                Auditoria auditoria = new Auditoria();
                var UserJson = Thread.CurrentPrincipal.Identity.Name;
                var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
                auditoria.IdUsuario = Deserialize.idUsuario;
                auditoria.Descripcion = $" Se genero Reproceso de NCFC para la tienda: {ls.Centro} con Fecha : {ls.FechaVenta} por el Usuario : {Deserialize.LoginName}" ;
                auditoria.Fecha = DateTime.Now;
                ng.Auditoria(auditoria);
            }

            return Json(resultado);
        }

        #region Proceso antiguo
        //Idoc Clientes
        //[HttpPost]
        //public async Task<JsonResult> GeneraIdoc(string Fecha, string local, string Documento,int Folio)
        //{

        //    if (local != "")
        //    {
        //        local = local.Replace("T0", "");

SistemaGestion/Views/Gestion/IdocClientes.cshtml
@{
    ViewBag.Title = "IdocClientes";
}



<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">IdocClientes</li>
                        </ol>
                    </nav>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card border-secondary">
                                <div class="card-header bg-secondary text-white">
                                   Generar Idoc de Clientes por Rut
                                </div>

                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="txtRucProveedor" class="col-form-label col-form-label-sm">Ingrese Rut</label>
                                                <input type="number" class="form-control form-control-sm model" id="txtFecha" name="txtFecha" autocomplete="off">
                                            </div>
                                        </div>
                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="btnBuscar" class="col-form-label col-form-label-sm invisible">Direccion:</label>
                                                <button id="btcarga" type="button" class="btn btn-sm btn-danger btn-block"><i class="fas fa-search"></i> Buscar</button>
                                            </div>
                                        </div>
                                      

                                    </div>

                                    <br />

                                </div>

                                <div class="alert alert-success" role="alert">
                                    Ingresar Rut sin Guiones ni Puntos
                                </div>

                                @if (ViewData["Mensaje"] != null)
                                {
                                    <div class="alert alert-danger" role="alert">
                                        @ViewData["Mensaje"]
                                    </div>
                                }


                            </div>

                        </div>

                    </div>

                </div>

            </main>
        </div>
    </div>
</body>


@section scripts{

    <script>

        $(document).ready(function () {


        })
        $(function (){
            $("#btcarga").click(function () {
                event.preventDefault();
                var result = confirm("Desea Generar Idoc?");
                if (result){
                    $('#cargal').modal('show');
                    var url = "@Url.Action("IdocClientes", "Gestion")";
                    var manejarErrorAjax = "Eror";
                    var Rut = $("#txtFecha").val();
                    var data = {rut: Rut };
                    $.post(url, data).done(function (resultado) {
                        $('#cargal').modal('hide');
                        if (resultado.error) {
                            swal(resultado.respuesta, "Presiona OK Para Continuar", "success");
                        } else {
                            swal(resultado.respuesta, "Presiona OK Para Continuar", "warning");
                        }
                        $("mensaje-alerta").html(resultado.respuesta)
                    }).fail(manejarErrorAjax);

                }

            });

        })


    </script>
}

SistemaGestion/Views/Gestion/LibroVenta.cshtml
@model List<SistemaGestion.Models.Proc_ListaLibroVenta_Result>
@{
    ViewBag.Title = "LibroVenta";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Reportes</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Ventas</li>
                        </ol>
                    </nav>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card border-secondary">
                                <div class="card-header bg-secondary text-white">
                                   Libro Venta Automatizado
                                </div>

                                <div class="card-body p-2">

                                    <div class="row">

                                        <div class="col-sm-3">
                                            <div class="form-group mb-0">
                                                <label for="txtRucProveedor" class="col-form-label col-form-label-sm">Tienda:</label>
                                                <select class="form-control form-control-sm model" id="cboTienda" name="Tienda"></select>
                                            </div>
                                        </div>
                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="txtRucProveedor" class="col-form-label col-form-label-sm">Fecha Para Ingresar:</label>
                                                <input type="date" class="form-control form-control-sm model" id="txtFecha" name="txtFecha" autocomplete="off" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                                            </div>
                                        </div>

                                        <div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="btnBuscar" class="col-form-label col-form-label-sm invisible">Direccion:</label>
                                                <button id="btnBuscar" type="button" class="btn btn-sm btn-danger btn-block"><i class="fas fa-search"></i> Buscar</button>
                                            </div>
                                        </div>


                                        @*<div class="col-sm-2">
                                            <div class="form-group mb-0">
                                                <label for="btnBuscar" class="col-form-label col-form-label-sm invisible">Direccion:</label>
                                                <button type="button" data-toggle="modal" id="VistaParcialLV" data-target="#Using" class="btn btn-sm btn-success btn-block">
                                                    <i class="fas fa-download"></i> Cargar Libro
                                                </button>
                                            </div>

                                        </div>*@

                                    </div>



                                    <div class="row mb-2">

                                    </div>

                                    <div id="diferencias">
                                        @if (Model.Count < 1)
                                        {
                                            <div class="container shadow-lg p-3 mb-5 mt-5 bg-body rounded">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <table id="tablaVacia" class="table table-bordered  display nowrap" cellspacing="0" width="100%">
                                                            <thead>
                                                                <tr>
                                                                    <th class="text-center">Sociedad</th>
                                                                    <th class="text-center">Centro</th>
                                                                    <th class="text-center">Documento</th>
                                                                    <th class="text-center">NumeroDocto</th>
                                                                    <th class="text-center">FechaContabilizacion</th>
                                                                    <th class="text-center">Referencia</th>
                                                                    <th class="text-center">Total</th>
                                                                    <th class="text-center">Impuesto</th>
                                                                    <th class="text-center">FechaDocumento</th>
                                                                    <th class="text-center">Cliente</th>
                                                                    <th class="text-center">NFis</th>
                                                                    <th class="text-center">Exe</th>
                                                                    <th class="text-center">Afe</th>
                                                                    <th class="text-center">Iva</th>

                                                                </tr>
                                                            </thead>
                                                            <tbody></tbody>

                                                        </table>
                                                        <div class="footer">
                                                            <div class="chart-legend">
                                                                <div class="text-center">
                                                                    <i class="fa fa-check-circle text-dark"></i>
                                                                    DB-Reversa Documento
                                                                    <i class="fa fa-check-circle text-dark"></i>
                                                                    DC-Recarga Minuto
                                                                    <i class="fa fa-check-circle text-dark"></i>
                                                                    DJ-Factura
                                                                    <i class="fa fa-check-circle text-dark"></i>
                                                                    DP-Boleta
                                                                    <i class="fa fa-check-circle text-dark"></i>
                                                                    DW-Nota de Credito
                                                                </div>

                                                            </div>

                                                        </div>

                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                                </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</body>

@section scripts{

    <script>
        $(document).ready(function () {
                $('#tablaVacia').DataTable(
                    {
                        responsive: true,
                        "language": {
                            url: "@Url.Content("~/Content/datatable/js/datatable_spanish.json")"
                        }
                    });

                $(function () {
                    $("#btnBuscar").click(function () {
                        event.preventDefault();
                        //var result = confirm("Desea Cargas Ventas?");
                        //  if (result){
                        $('#cargal').modal('show');
                        var url = "@Url.Action("AdminLibro", "Gestion")";
                        var manejarErrorAjax = "Eror";
                        var Fecha = $("#txtFecha").val();
                        var local = $("#cboTienda").val()
                        var data = { Fecha: Fecha, local:local};
                        $.post(url, data).done(function (data) {
                            setTimeout(bajar, 1000);
                            setTimeout(Subir, 2000);

                            function bajar() {
                                $('#cargal').modal('hide');

                            }
                            function Subir() {
                                $('#diferencias').html(data);
                                $('#diferencias').show();
                            }

                        }).fail(manejarErrorAjax);

                        //}
                    });

                })

            jQuery.ajax({
                url: $.MisUrls.url._TiendaPorNombre,
                type: "GET",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $("<option>").attr({ "value": 0 }).text("-- Seleccionar todas--").appendTo("#cboTienda");
                    $.each(data.data, function (i, item) {
                        $("<option>").attr({ "value": item.Centro }).text(item.Nombre_Centro).appendTo("#cboTienda");

                    })
                },
                error: function (error) {
                    console.log(error)
                },

            });

            });

         $(function () {
        $("#btcargalibro").click(function () {
            event.preventDefault();
            var result = confirm("Desea Cargar Libro de Venta?");
            if (result) {
                $('#carga').modal('show');
                var url = "@Url.Action("CargaLibro", "Gestion")";
                var manejarErrorAjax = "Eror";
                //alert("Cargando Libro de Venta");
                $.post(url).done(function (resultado) {
                    setTimeout(bajar, 1000);
                    setTimeout(Subir, 2000);
                    function bajar() {

                        $('#carga').modal('hide');


                    }
                    function Subir() {
                        //$('#totales').html(data);
                        //$('#totales').show();

                    }
                    //$('#carga').modal('hide');
                    if (resultado.error) {
                        swal(resultado.respuesta, "Presiona OK Para Continuar", "success");
                    } else {
                        swal(resultado.respuesta, "Presiona OK Para Continuar", "warning");
                    }
                    $("mensaje-alerta").html(resultado.respuesta)
                    Location.reload();
                }).fail(manejarErrorAjax);
            }

        });

    })



    </script>




}

SistemaGestion/Views/Gestion/_Ventas.cshtml
@model List<SistemaGestion.Models.Proc_ListaIdocVenta_Result>
<div class="container shadow-lg p-3 mb-5 mt-5 bg-body rounded">
    <div class="row">
        <div class="col-lg-12">
            <table id="tbReporte" class="table table-bordered  display nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th class="text-center">Centro</th>
                        <th class="text-center">Local</th>
                        <th class="text-center">Estado</th>
                        <th class="text-center">Observacion</th>
                        <th class="text-center">Fecha</th>
                        <th class="text-center">Archivo_Idoc</th>
                        <th class="text-center">ID_Proceso</th>
                        <th class="text-center">FechaHora</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>

                        <td>@item.Centro</td>
                        <td>@item.Local</td>
                        <td>@item.Estado</td>
                        <td>@item.Observacion</td>
                        <td>@item.Fecha</td>
                        <td>@item.Archivo_IDOC</td>
                        <td>@item.ID_Proceso</td>
                        <td>@item.FechaHora</td>



                    </tr>
                    }
                </tbody>

            </table>



        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        var tabla_data;
        tabla_data = $('#tbReporte').DataTable({
            responsive: true,
            "language": {
                url: "@Url.Content("~/Content/datatable/js/datatable_spanish.json")"
            }
        });
    });
</script>