SistemaGestion/Controllers/TesoreriaController.cs
using Newtonsoft.Json;
using OfficeOpenXml;
using Rotativa.MVC;
using SistemaGestion.Models;
using SistemaGestion.Models.DAO;
using SistemaGestion.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SistemaGestion.Controllers
{
    public class TesoreriaController : Controller
    {
        #region Objetos
        private SisGesEntities3 db = new SisGesEntities3();
        private LibroVentaRepository carga = new LibroVentaRepository();
        private TesoreriaConciliacion Teo = new TesoreriaConciliacion();
        private Negocio Ng = new Negocio();
        #endregion
        // GET: Tesoreria
        public ActionResult Index()
        {
           
            return View();
        }
        [HttpPost]
        public ActionResult Index(DateTime Inicio, DateTime Fin)
        {
            var model = db.Sencillos.Where(x=>x.FechaInicio >= Inicio && x.FechaFin <= Fin).ToList();
            return PartialView("_SencillosCargados",model);
        }



        public ActionResult CargaCartaInstruccion()
        {
            return PartialView("_CargaCartaInstruccion");
        }

        public ActionResult CargaSencillo()
        {
            return PartialView("_CargaSencilloSAP");
        }

        [HttpPost]
        public ActionResult DetailsSencillo(Guid Id)
        {
            //var prueba = Guid.Parse(id);
            var model = db.DetalleSencillo.Where(x => x.IdSencillo == Id).OrderBy(x=>x.IdTienda).ToList();
            return PartialView("_DetailsSencillo", model);
        }

        [HttpPost]
        public ActionResult PDFTesoreria(Guid Id)
        {
            //var prueba = Guid.Parse(id);
            var model = db.DetalleSencillo.Where(x => x.IdSencillo == Id).OrderBy(x => x.IdTienda).ToList();
            return new ViewAsPdf("PDFTesoreria", model)
            {
                FileName = $"Tesoreria.pdf"
            };
        }

        [HttpPost]
        public async Task<ActionResult> saveCartaInstruccion(CargaSencilloView SencilloT)
        {
            ResponseModel response = new ResponseModel();
            Sencillos sn = db.Sencillos.Where(x => x.FechaInicio == SencilloT.Inicio || x.FechaFin == SencilloT.Fin).FirstOrDefault();

            if (sn !=null)
            {
                response.error = true;
                response.respuesta = "El periodo Ingresado ya se realizo, Elimina el periodo si deseas a volver a cargar";
                return Json(response);
            }

            if (SencilloT.Inicio == SencilloT.Fin)
            {
                response.error = true;
                response.respuesta = "Las Fechas de Carga No pueden ser Iguales";
                return Json(response);
            }

            if (SencilloT.Fin < SencilloT.Inicio)
            {
                response.error = true;
                response.respuesta = "La Fecha de Fin no puede ser menor a la Fecha de Inicio";
                return Json(response);
            }


            if (SencilloT.oFile == null)
            {
                response.error = true;
                response.respuesta = "Debe cargar un archivo";
                return Json(response);
            }
            string extension = Path.GetExtension(SencilloT.oFile.FileName);

            if (extension.Equals(".xlsx"))
            {
                string ruta = Server.MapPath("~/File/");
                if (!System.IO.Directory.Exists(ruta + "CartaInstruccion"))
                {
                    System.IO.Directory.CreateDirectory(ruta + "CartaInstruccion");
                }
                response = carga.CargaCartaInstruccion(SencilloT, ruta);
                response.error = false;
          
                if (!response.error)
                {
                    Auditoria auditoria = new Auditoria();
                    var UserJson = Thread.CurrentPrincipal.Identity.Name;
                    var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
                    auditoria.IdUsuario = Deserialize.idUsuario;
                    Persona username = db.Persona.Where(x => x.Id == Deserialize.idUsuario).FirstOrDefault();
                    auditoria.Descripcion = "Se Cargo la carta de Instruccion por el usuario : " + Deserialize.LoginName + " - "  + username.Nombre;
                    auditoria.Fecha = DateTime.Now;
                    //Ng.Auditoria(auditoria);

                    await Ng.GetAlertaCartaInstruccion(auditoria.Descripcion, SencilloT.Inicio,SencilloT.Fin);
                }
            }
            else
            {
                response.error = true;
                response.respuesta = "La extencion no es correcta";
            }


            return Json(response);
        }


        [HttpPost]
        public ActionResult saveSencillosSAP(HttpPostedFileBase oFile)
        {
            ResponseModel response = new ResponseModel();
            //List<SencillosSAP> sp = db.SencillosSAP.Where(x => x.Fecha_Doc >= SencilloT.Inicio && x.Fecha_Doc <= SencilloT.Fin).ToList();
            //if (sp != null)
            //{
            //    response.error = true;
            //    response.respuesta = "El periodo Ingresado ya se realizo, Elimina el periodo si deseas a volver a cargar";
            //    return Json(response);
            //}
            //if (SencilloT.Inicio == SencilloT.Fin)
            //{
            //    response.error = true;
            //    response.respuesta = "Las Fechas de Carga No pueden ser Iguales";
            //    return Json(response);
            //}

            //if (SencilloT.Fin < SencilloT.Inicio)
            //{
            //    response.error = true;
            //    response.respuesta = "La Fecha de Fin no puede ser menor a la Fecha de Inicio";
            //    return Json(response);
            //}

            //if (SencilloT.oFile == null)
            //{
            //    response.error = true;
            //    response.respuesta = "Debe cargar un archivo";
            //    return Json(response);
            //}
            string extension = Path.GetExtension(oFile.FileName);

            if (extension.Equals(".xlsx"))
            {
                string ruta = Server.MapPath("~/File/");
                if (!System.IO.Directory.Exists(ruta + "CartaInstruccion"))
                {
                    System.IO.Directory.CreateDirectory(ruta + "CartaInstruccion");
                }
                response = carga.CargaSencillo(oFile, ruta);
            }
            else
            {
                response.error = true;
                response.respuesta = "La extencion no es correcta";
            }


            return Json(response);
        }

        public ActionResult ConciliacionSencillo()
        {
            return View();
        }

       

        public ActionResult ConciliacionAutomatica(DateTime Inicio, DateTime Fin)
        {
            List<SencillosSAPView> lst = new List<SencillosSAPView>();
            lst = Teo.ListaCuadraturaTesoreria(Inicio,Fin).ToList();
            return PartialView("_ConciliadasAutomatica",lst);
        }
        [HttpPost]
        public ActionResult ConciliacionSencillosSAP(DateTime Inicio, DateTime Fin)
        {
            ResponseModel response = new ResponseModel();
            response = Teo.ConciliarSencillos(Inicio, Fin);
            return Json(response);
        }

        [HttpPost]
        public JsonResult ValidadorConciliacionAuto(DateTime Inicio, DateTime Fin)
        {

            Sencillos lst = new Sencillos();
            lst = Teo.ValidarConciliacion(Inicio, Fin);
            var resultado = new ResponseModel();
            var xsw = lst.DetalleSencillo.Any(x => x.ConciliacionTesoreria == true);
            resultado = Teo.ConciliarSencillos(Inicio, Fin);
            if (!resultado.error)
            {
                Auditoria auditoria = new Auditoria();
                var UserJson = Thread.CurrentPrincipal.Identity.Name;
                var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
                auditoria.IdUsuario = Deserialize.idUsuario;
                auditoria.Descripcion = "Se Genero Reproceso de la Conciliacion Sencillos SAP Pagos por el usurio :" + Deserialize.LoginName;
                auditoria.Fecha = DateTime.Now;
                Ng.Auditoria(auditoria);
            }
            return Json(resultado);
            //if (lst.DetalleSencillo.Any(x => x.ConciliacionTesoreria == true))
            //{
            //    resultado.error = false;
            //    resultado.respuesta += "Estas Fecha : " + Inicio.ToString("dd-MM-yyyy") + Fin.ToString("dd-MM-yyyy") + " ya fueron conciliada, El dia :"+ lst.Fecha.Value.ToString("dd-MM-yyyy");
            //    return Json(resultado);
            //}
            //else
            //{
            //    resultado = Teo.ConciliarSencillos(Inicio,Fin);
            //    if (!resultado.error)
            //    {
            //        Auditoria auditoria = new Auditoria();
            //        var UserJson = Thread.CurrentPrincipal.Identity.Name;
            //        var Deserialize = JsonConvert.DeserializeObject<UserLoginView>(UserJson);
            //        auditoria.IdUsuario = Deserialize.idUsuario;
            //        auditoria.Descripcion = "Se Genero Reproceso de la Conciliacion Sencillos SAP Pagos por el usurio :" + Deserialize.LoginName;
            //        auditoria.Fecha = DateTime.Now;
            //        Ng.Auditoria(auditoria);
            //    }
            //    return Json(resultado);
            //}

        }

        public ActionResult NoConciliacion(DateTime Inicio, DateTime Fin)
        {
            List<fnSencillosTiendaNoConciliados_Result> lst = new List<fnSencillosTiendaNoConciliados_Result>();
            lst = Teo.Noconciliadas(Inicio,Fin).ToList();

SistemaGestion/Views/Tesoreria/_CargaCartaInstruccion.cshtml
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
                Carga Carta Instruccion
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @using (Html.BeginForm("saveCartaInstruccion", "Tesoreria", FormMethod.Post, new { id = "saveCartaInstruccion", role = "form", enctype = "multipart/form-data" }))
        {
    <div class="modal-body">
        <div class="form-group col-md-4">
            <div class="form-group mb-3">
                <label for="txtRucProveedor" class="col-form-label col-form-label-sm">Fecha Inicio :</label>
                <input type="date" class="form-control form-control-sm model" id="Inicio" name="Inicio" autocomplete="off" value="@DateTime.Today.ToString("yyyy-MM-dd")">
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="form-group mb-3">
                <label for="txtRucProveedor" class="col-form-label col-form-label-sm">Fecha Fin:</label>
                <input type="date" class="form-control form-control-sm model" id="Fin" name="Fin" autocomplete="off" value="@DateTime.Today.ToString("yyyy-MM-dd")">
            </div>
        </div>
        <div class="form-group col-md-6">
            <label>Adjuntar Carta Instruccion</label>
            <INPUT id="oFile" type="file" runat="server" NAME="oFile" accept="application/xlsx">
        </div>
    </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="Cargarlv">Cargar Libro</button>
            </div>
        }

    </div>
</div>

    <script>
        $(document).ready(function () {
            $('#Cargarlv').click(function () {
                event.preventDefault();
                $('#cargal').modal('show');
                var para = new FormData($(saveCartaInstruccion).get(0));
                console.log(para);
                var url = '@Url.Action("saveCartaInstruccion", "Tesoreria")';
                $.ajax({
                    type: 'POST',
                    url: url,
                    //async: false,
                    processData: false,
                    contentType: false,
                    data: para,
                    success: function (r) {
                        if (r.error == false) {

                            setTimeout(carga, 3000);
                           /* setTimeout(CerrarVistaP, 10000);*/
                            setTimeout(mostrarMensaje, 4000);
                            setTimeout(bajaModal, 6000);
                            function carga() {

                                $("#cargal").modal('hide');

                            };
                            //function CerrarVistaP() {
                            //    $('#modal').modal('hide');
                            //};
                            function bajaModal() {
                                $('#cargarMensajes').modal('hide');
                                $('#modal').modal('hide');


                            };

                            function mostrarMensaje() {
                                $("#cargarMensajes").modal('show');
                                $('#mensajeLoad').html(r.respuesta);

                            };


                        }
                        else {
                            setTimeout(carga, 3000);
                            setTimeout(mostrarMensaje, 4000);
                            setTimeout(bajaModal, 6000);
                            function carga() {
                                $("#cargal").modal('hide');
                                //$("#cargarMensajes").modal('show');
                                //$('#mensajeLoad').html(r.respuesta);
                            };
                            function bajaModal() {

                                $("#cargarMensajes").modal('hide');

                            };

                            function mostrarMensaje() {
                                $("#cargarMensajes").modal('show');
                                $('#mensajeLoad').html(r.respuesta);

                            };
                        }


                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError);
                    }
                });

            });
        });
    </script>

SistemaGestion/Views/Tesoreria/_CargaSencilloSAP.cshtml
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
               Cargar Sencillos de SAP
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @using (Html.BeginForm("saveCartaInstruccion", "Tesoreria", FormMethod.Post, new { id = "saveCartaInstruccion", role = "form", enctype = "multipart/form-data" }))
        {


    <div class="modal-body">
        
       
        <div class="form-group col-md-6">
            <label>Adjuntar Sencillos de SAP</label>
            <INPUT id="oFile" type="file" runat="server" NAME="oFile" accept="application/xlsx">




        </div>
    </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="Cargarlv">Cargar Libro</button>
            </div>
        }

    </div>
</div>

<script>
        $(document).ready(function () {
            $('#Cargarlv').click(function () {
                event.preventDefault();
                $('#cargal').modal('show');

                var para = new FormData($(saveCartaInstruccion).get(0));
                var url = '@Url.Action("saveSencillosSAP", "Tesoreria")';
                $.ajax({
                    type: 'POST',
                    url: url,
                    //async: false,
                    processData: false,
                    contentType: false,
                    data: para,
                    success: function (r) {
                        if (r.error == false) {

                            setTimeout(carga, 3000);
                           /* setTimeout(CerrarVistaP, 10000);*/
                            setTimeout(mostrarMensaje, 4000);
                            setTimeout(bajaModal, 6000);
                            function carga() {

                                $("#cargal").modal('hide');

                            };
                            //function CerrarVistaP() {
                            //    $('#modal').modal('hide');
                            //};
                            function bajaModal() {
                                $('#cargarMensajes').modal('hide');
                                $('#modal').modal('hide');


                            };

                            function mostrarMensaje() {
                                $("#cargarMensajes").modal('show');
                                $('#mensajeLoad').html(r.respuesta);

                            };


                        }
                        else {
                            setTimeout(carga, 3000);
                            setTimeout(mostrarMensaje, 4000);
                            setTimeout(bajaModal, 6000);
                            function carga() {
                                $("#cargal").modal('hide');
                                //$("#cargarMensajes").modal('show');
                                //$('#mensajeLoad').html(r.respuesta);
                            };
                            function bajaModal() {

                                $("#cargarMensajes").modal('hide');

                            };

                            function mostrarMensaje() {
                                $("#cargarMensajes").modal('show');
                                $('#mensajeLoad').html(r.respuesta);

                            };
                        }


                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError);
                    }
                });

            });
        });
</script>

SistemaGestion/Views/Tesoreria/_NoConciliadas.cshtml
@model List<SistemaGestion.Models.fnSencillosTiendaNoConciliados_Result>

<div class="container shadow-lg p-3 mb-5 mt-5 bg-body rounded">
    <div class="row">
        <div class="col-lg-12">
            <div class="mt-3 mb-2 mr-1 float-right ">
                <button type="button" id="btnSendData" class="btn btn-sm btn-danger btn-block">
                    <i class="fa fa-bell"></i> Generar Alertas<span class="glyphicon glyphicon-arrow-right"></span>
                </button>
            </div>
            <table id="tbReporte" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th class="text-center">Tienda</th>
                        <th class="text-center">Total</th>
                        <th class="text-center">Banco</th>
                        <th class="text-center">DiaLiberacion</th>
                        <th class="text-center">DiaEntrega</th>
                        <th class="text-center">FechaInicio</th>
                        <th class="text-center">FechaFin</th>
                        <th class="text-center">Estado</th>


                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.idtienda</td>
                            <td>@item.NuevoTotal</td>
                            <td>@item.Banco</td>
                            <td>@item.DiaLiberacion</td>
                            <td>@item.DiaEntrega</td>
                            <td>@item.FechaInicio.Value.ToString("dd-MM-yyyy")</td>
                            <td>@item.FechaFin.Value.ToString("dd-MM-yyyy")</td>
                            <td class="bg-danger text-white">Sin Conciliar</td>





                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        $('table.display').DataTable({
            responsive: true,
             "language": {
                   url: "@Url.Content("~/Content/datatable/js/datatable_spanish.json")"
               }
        });

         $(function (){
             $("#btnSendData").click(function () {
                event.preventDefault();
                var result = confirm("Desea enviar Alertas?");
                if (result){
                    $('#cargal').modal('show');
                    var url = "@Url.Action("Alertas", "Tesoreria")";
                    var manejarErrorAjax = "Eror";
                    var Fecha = $("#Fecha").val();
                    var data = { Fecha: Fecha};
                    $.post(url, data).done(function (res) {
                        if (res.error == false) {
                           
                            setTimeout(carga, 3000);
                            /* setTimeout(CerrarVistaP, 10000);*/
                            setTimeout(mostrarMensaje, 4000);
                            setTimeout(bajaModal, 6000);
                            function carga() {

                                $("#cargal").modal('hide');

                            };
                            //function CerrarVistaP() {
                            //    $('#modal').modal('hide');
                            //};
                            function bajaModal() {
                                $('#cargarMensajes').modal('hide');
                                $('#modal').modal('hide');


                            };

                            function mostrarMensaje() {
                                $("#cargarMensajes").modal('show');
                                $('#mensajeLoad').html(res.respuesta);

                            };
                        }
                        else {
                            setTimeout(carga, 3000);
                            setTimeout(mostrarMensaje, 4000);
                            setTimeout(bajaModal, 6000);
                            function carga() {
                                $("#cargal").modal('hide');
                                //$("#cargarMensajes").modal('show');
                                //$('#mensajeLoad').html(r.respuesta);
                            };
                            function bajaModal() {

                                $("#cargarMensajes").modal('hide');

                            };

                            function mostrarMensaje() {
                                $("#cargarMensajes").modal('show');
                                $('#mensajeLoad').html(res.respuesta);

                            };
                        }


                    }).fail(manejarErrorAjax);

                }
            });

        })

    });

</script>

SistemaGestion/Views/Tesoreria/_SencillosCargados.cshtml
@model  List<SistemaGestion.Models.Sencillos>
<div class="container shadow-lg p-3 mb-5 mt-5 bg-body rounded">
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="Sencillos" class="table table-bordered table-hover" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    @*<th class="text-center">Id</th>*@
                                    <th class="text-center">Fecha de Carga</th>
                                    <th class="text-center">Fecha Periodo Inicio</th>
                                    <th class="text-center">Fecha Periodo FIN</th>
                                    <th class="text-center">Accion</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var a in Model)
                                {
                                    <tr>
                                        @*<td class="text-center">@a.Id</td>*@
                                        <td class="text-center">@a.Fecha</td>
                                        <td class="text-center">@a.FechaInicio</td>
                                        <td class="text-center">@a.FechaFin</td>
                                        <td class="text-center">
                                            <button type='button' class='editar btn btn-outline-info btn-sm shadow-sm' title="Detalle"
                                                    onclick="DetalleBySencillo('@a.Id')">
                                                <span class='fa fa-list-alt'></span>
                                            </button>
                                            <button type='button' class='editar btn btn-outline-danger btn-sm shadow-sm' title="Eliminar"
                                                    onclick="Eliminar('@a.Id')">
                                                <span class='fa fa-trash'></span>
                                            </button>
                                            @*<button type='button' class='editar btn btn-outline-danger btn-sm shadow-sm' title="PDF"
        onclick="PDF('@a.Id')">
                <span class='fa fa-file-pdf'></span>
               </button>*@
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
<div class="modal fade" id="ModalDetalle" role="dialog">
</div>

<script>
    $(document).ready(function () {
        $('#Sencillos').DataTable({
            responsive: true,
             "language": {
                   url: "@Url.Content("~/Content/datatable/js/datatable_spanish.json")"
               }
        });



    });
    function DetalleBySencillo(Id) {
            console.log('entro aca');
            console.log(Id)
        //var data = { fecha: fecha, idCencos: cencos, idZona: zona, nomCenco: nomCencos};
         var url = "@Url.Action("DetailsSencillo", "Tesoreria")";
            $.ajax({
                type: 'POST',
                url: url,
                data: { Id: Id },
            success: function (response) {
                $("#ModalDetalle").html(response);
                $("#ModalDetalle").modal('show');
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(thrownError);
            }
        });
    }

    function Eliminar(Id) {
            console.log('entro aca');
            console.log(Id)
        //var data = { fecha: fecha, idCencos: cencos, idZona: zona, nomCenco: nomCencos};
        $('#cargal').modal('show');
         var url = "@Url.Action("EliminarCarta", "Tesoreria")";
            $.ajax({
                type: 'POST',
                url: url,
                data: { Id: Id },
                success: function (response) {
                    if (response == false) {
                        setTimeout(carga, 3000);
                /* setTimeout(CerrarVistaP, 10000);*/
                setTimeout(mostrarMensaje, 4000);
                        setTimeout(bajaModal, 6000);
                        console.log("entro eliminar")
                function carga() {

                    $("#cargal").modal('hide');

                };

                function bajaModal() {
                    $('#cargarMensajes').modal('hide');
                    $('#modal').modal('hide');


                };

                function mostrarMensaje() {
                    $("#cargarMensajes").modal('show');
                    $('#mensajeLoad').html(response.respuesta);

                };
                    }
                    else {
                        setTimeout(carga, 3000);
                        setTimeout(mostrarMensaje, 4000);
                        setTimeout(bajaModal, 6000);

                        function carga() {
                            $("#cargal").modal('hide');
                            //$("#cargarMensajes").modal('show');
                            //$('#mensajeLoad').html(r.respuesta);
                        };
                        function bajaModal() {

                            $("#cargarMensajes").modal('hide');

                        };

                        function mostrarMensaje() {
                            bajarModalDiferencias();
                            $("#cargarMensajes").modal('show');
                            $('#mensajeLoad').html(response.respuesta);

                        };

                    }

            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(thrownError);
            }
        });
    }

                function bajarModalDiferencias() {
                 console.log("Entrea bajar el modal");
                     var Inicio = $("#Inicio").val();
                        var Fin = $("#Fin").val();
                        if (Inicio == Fin || Fin == Inicio ) {
                            alert("Las Fechas no pueden ser Iguales")
                            return 0;
                        }
                        if (Fin < Inicio) {
                            alert("Las Fecha de Fin no puede ser menor que la Fecha de Inicio")
                            return 0;
                        }
                        $('#cargal').modal('show');
                        var url = "@Url.Action("Index", "Tesoreria")";
                        var manejarErrorAjax = "Eror";

                        var data = { Inicio: Inicio, Fin: Fin};
                        $.post(url, data).done(function (data) {
                            setTimeout(bajar, 1000);
                            setTimeout(Subir, 2000);

                            function bajar() {
                                $('#cargal').modal('hide');

                            }
                            function Subir() {
                                $('#diferencias').html(data);
                                $('#diferencias').show();
                            }

                        }).fail(manejarErrorAjax);

        }

</script>